### ISSUE TITLE
Added value compared to chai-changes?

### ISSUE THREAD

**Issue by matthijsgroen** [chaijs/chai-change#2]
What can chai-change do what chai-changes cannot?

https://github.com/matthijsgroen/chai-changes

**Comment by jrodriguesimg** [comment]
The main advantage of this package is that it supports promises both on the expect and the alter. The chai-changes package only accepts promises in the alter (when).

PS: I know this issue is closed but hopefully it will save someone the trouble of trying the chai-changes package.
